name: Build and test plugin for specified IDE
on:
  workflow_call:
    inputs:
      ide:
        required: false
        type: string

jobs:
  build-and-test-plugin:
    runs-on: ubuntu-latest

    steps:
      # Deletable toolchain directories taken from https://github.com/easimon/maximize-build-space
      - name: Maximize build space
        run: >
          sudo rm -rf /usr/share/dotnet &&
          sudo rm -rf /usr/local/lib/android &&
          sudo rm -rf /opt/ghc &

      - name: Configure IDE flag
        run: |
          if [[ -n ${{ inputs.ide }} && ${{ inputs.ide }} != "intellij" ]]; then
            echo "ORG_GRADLE_PROJECT_ide=${{ inputs.ide }}" >> $GITHUB_ENV
          fi

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          java-package: jdk

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Project
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew test

      - name: Grab IDE Versions To Verify Against
        run: ./gradlew listProductsReleases

      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.pluginVerifier/ides
          key: plugin-verifier-${{ inputs.ide }}-${{ hashFiles('build/listProductsReleases.txt') }}

      - name: Run Plugin Verification
        run: ./gradlew runPluginVerifier
