name: Build
on: [push]

jobs:
  build-intellij:
    uses: ./.github/workflows/build-and-test-plugin.yml
    with:
      ide: intellij

  build-clion:
    uses: ./.github/workflows/build-and-test-plugin.yml
    with:
      ide: clion
