name: Build, Test & Verify Plugin
on:
  push:
  schedule:
    - cron: "0 19 1 * *"

jobs:
  build-intellij:
    uses: ./.github/workflows/build-and-test-plugin.yml
    with:
      ide: intellij

  build-clion:
    uses: ./.github/workflows/build-and-test-plugin.yml
    with:
      ide: clion
